component_depth: 1
languages:
- java
exclude:
- ./conf/.*
- ./doc/.*
- ./doc/coverageresults/.*
- ./doc/coverageresults/css/.*
- ./doc/coverageresults/images/.*
- ./doc/coverageresults/js/.*
- ./doc/javadoc/.*
- ./doc/javadoc/org/.*
- ./doc/javadoc/org/jfin/.*
- ./doc/javadoc/org/jfin/common/.*
- ./doc/javadoc/org/jfin/date/.*
- ./doc/javadoc/org/jfin/date/accrual/.*
- ./doc/javadoc/org/jfin/date/accrual/impl/.*
- ./doc/javadoc/org/jfin/date/daycount/.*
- ./doc/javadoc/org/jfin/date/daycount/defaultimpl/.*
- ./doc/javadoc/org/jfin/date/holiday/.*
- ./doc/javadoc/org/jfin/date/holiday/defaultimpl/.*
- ./doc/javadoc/org/jfin/date/holiday/financialcalendarimpl/.*
- ./doc/javadoc/org/jfin/date/util/.*
- ./doc/junitresults/.*
- ./doc/junitresults/org/.*
- ./doc/junitresults/org/jfin/.*
- ./doc/junitresults/org/jfin/common/.*
- ./doc/junitresults/org/jfin/common/test/.*
- ./doc/junitresults/org/jfin/date/.*
- ./doc/junitresults/org/jfin/date/test/.*
- ./doc/junitresults/org/jfin/date/test/accrual/.*
- ./doc/junitresults/org/jfin/date/test/accrual/impl/.*
- ./doc/junitresults/org/jfin/date/test/daycount/.*
- ./doc/junitresults/org/jfin/date/test/daycount/defaultimpl/.*
- ./doc/junitresults/org/jfin/date/test/holiday/.*
- ./doc/junitresults/org/jfin/date/test/holiday/defaultimpl/.*
- ./doc/junitresults/org/jfin/date/test/holiday/financialcalendarimpl/.*
- ./doc/junitresults/org/jfin/date/test/util/.*
- ./doc/junitresults/org/jfin/date/test/web/.*
- ./doc/junitresults/org/jfin/date/test/web/example/.*
- ./doc/uml/.*
- ./doc/uml/accrual/.*
- ./doc/uml/daycount/.*
- ./doc/uml/holiday/.*
- ./examples/.*
- ./examples/lib/.*
